spring:
  cloud:
    discovery:
      client:
        simple:
          instances:
            test:
              - uri: http://localhost:9000
                metadata:
                  management.context-path: /actuator
